/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.10_dev
 * Thu Nov  1 01:53:05 2007
 */
#define AUTOCONF_INCLUDED

/*
 * Motorola Features and Bug Fixes
 */
#define CONFIG_MOT_WFN478 1
#define CONFIG_MOT_FEAT_BRDREV 1
#define CONFIG_MOT_FEAT_BOOTINFO 1
#define CONFIG_MOT_WFN430 1
#define CONFIG_MOT_FEAT_DOWN_TIMEOUT 1
#define CONFIG_MOT_FEAT_POWERUP_LOGO 1
#define CONFIG_MOT_FEAT_POWERUP_REASON_EZX_COMPAT 1
#define CONFIG_MOT_FEAT_MTD_FS 1
#define CONFIG_MOT_FEAT_LPNAND_SUPPORT 1
#undef CONFIG_MOT_WFN439
#define CONFIG_MOT_FEAT_NAND_AUTO_DETECT 1
#undef CONFIG_MOT_FEAT_FB_MXC_RGB
#define CONFIG_MOT_FEAT_FB_MXC_BGR 1
#define CONFIG_MOT_FEAT_IPU_BGRA6666 1
#undef CONFIG_MOT_FEAT_EMULATED_CLI
#define CONFIG_MOT_FEAT_LCD_ESD_RECOVERY 1
#define CONFIG_MOT_WFN394 1
#define CONFIG_MOT_WFN429 1
#define CONFIG_MOT_FEAT_IPU_PF_PERM666 1
#define CONFIG_MOT_FEAT_DISABLE_SW_CURSOR 1
#define CONFIG_MOT_FEAT_SYSREBOOT 1
#undef CONFIG_MOT_WFN432
#define CONFIG_MOT_WFN435 1
#define CONFIG_MOT_FIX_ASCENSION 1
#define CONFIG_MOT_FEAT_IPU_MEM_ADDR 1
#define CONFIG_MOT_FEAT_IPU_IOCTL 1
#define CONFIG_MOT_FEAT_FB_PANIC_TEXT 1
#define CONFIG_MOT_FEAT_IPU_IOCTL_EZX_COMPAT 1
#undef CONFIG_MOT_WFN418
#define CONFIG_MOT_FEAT_ACTIVE_AND_LOW_POWER_INTERVAL_TIMERS 1
#undef CONFIG_MOT_FEAT_PRINTK_TIMES
#undef CONFIG_MOT_WFN248
#define CONFIG_MOT_FEAT_ADVANCED_DEBUG 1

/*
 * Advanced Debugging Options
 */
#define CONFIG_MOT_FEAT_KPANIC 1
#define CONFIG_MOT_FEAT_DEBUG_WDOG 1
#undef CONFIG_MOT_FEAT_MEMDUMP
#undef CONFIG_MOT_FEAT_TEST_PANIC
#undef CONFIG_MOT_FEAT_PANIC_ON_OOPS
#undef CONFIG_MOT_FEAT_PANIC_ON_SCHED_ATOMIC
#define CONFIG_MOT_FEAT_MODEM_RELAY 1
#define CONFIG_MOT_KEYPAD 1
#undef CONFIG_MOT_FEAT_FLIP
#define CONFIG_MOT_FEAT_SLIDER 1
#undef CONFIG_MOT_FEAT_CANDYBAR
#define CONFIG_MOT_FEAT_PPP_EZX_COMPAT 1
#define CONFIG_MOT_FEAT_SLABFREE_PROC 1
#define CONFIG_MOT_FEAT_MXC_IPC_SDMA_STATS 1
#define CONFIG_MOT_WFN244 1
#define CONFIG_MOT_FEAT_APP_DUMP 1
#define CONFIG_MOT_FEAT_PM 1
#define CONFIG_MOT_FEAT_PM_DESENSE 1
#define CONFIG_MOT_FEAT_PM_STATS 1
#undef CONFIG_MOT_FEAT_PM_DEVICE_SUSPEND_DEBUG
#define CONFIG_PROFILER 1
#define CONFIG_MOT_FEAT_SET_MAC 1
#define CONFIG_MOT_FEAT_NAND_RDDIST 1
#undef CONFIG_MOT_FEAT_NAND_BLKCNT_TEST
#undef CONFIG_MOT_FEAT_NANDECC_TEST
#define CONFIG_MOT_WFN349 1
#define CONFIG_MOT_FEAT_SO_BINDTODEVICE_EZX_COMPAT 1
#undef CONFIG_MOT_FEAT_MU_TEST
#define CONFIG_MOT_WFN374 1
#define CONFIG_MOT_WFN381 1
#define CONFIG_MOT_FEAT_SECURE_CLOCK 1
#define CONFIG_MOT_WFN377 1
#define CONFIG_MOT_FEAT_OTP_EFUSE 1
#define CONFIG_MOT_FEAT_ATLAS_TIMING_ISSUES 1
#undef CONFIG_MOT_WFN396
#undef CONFIG_MOT_WFN428
#define CONFIG_MOT_WFN470 1
#define CONFIG_MOT_FEAT_CONSOLE_DISABLED 1
#define CONFIG_MOT_FEAT_CHKSUM 1
#define CONFIG_MOT_WFN379 1
#define CONFIG_MOT_WFN406 1
#define CONFIG_MOT_FEAT_BT_MAXUARTBAUDRATE 1
#define CONFIG_MOT_WFN408 1
#define CONFIG_MOT_WFN404 1
#define CONFIG_MOT_WFN403 1
#define CONFIG_MOT_WFN409 1
#define CONFIG_MOT_WFN407 1
#define CONFIG_MOT_FEAT_FX2LP_I2C 1
#undef CONFIG_MOT_WFN423
#define CONFIG_MOT_FEAT_SECURE_USERMEM 1
#define CONFIG_MOT_FEAT_NO_PTRACE 1
#define CONFIG_MOT_FEAT_LSM 1
#define CONFIG_MOT_FEAT_SECURE_MOUNT 1
#define CONFIG_MOT_FEAT_SECURE_MOUNT_SYSFS_MODULE 1
#define CONFIG_MOT_FEAT_PANIC_DECISION 1
#define CONFIG_MOT_FEAT_SECURE_DRM 1
#define CONFIG_MOT_FEAT_SECURE_MODULE 1
#undef CONFIG_MOT_FEAT_DISABLE_UART3_DMA
#define CONFIG_MOT_FEAT_GPIO_API 1

/*
 * GPIO API Options
 */
#undef CONFIG_MOT_FEAT_ANTIVIRUS_HOOKS
#undef CONFIG_MOT_FEAT_GPIO_TRACE
#define CONFIG_MOT_FEAT_GPIO_API_EDIO 1
#define CONFIG_MOT_FEAT_GPIO_API_MC13783 1
#define CONFIG_MOT_FEAT_GPIO_API_BTPOWER 1
#define CONFIG_MOT_FEAT_GPIO_API_CSI 1
#define CONFIG_MOT_FEAT_GPIO_API_DAI 1
#undef CONFIG_MOT_FEAT_GPIO_API_ETHERNET
#undef CONFIG_MOT_FEAT_GPIO_API_ETM
#define CONFIG_MOT_FEAT_GPIO_API_LCD 1
#define CONFIG_MOT_FEAT_GPIO_API_LIGHTING 1

/*
 * GPIO Lighting API Options
 */
#undef CONFIG_MOT_FEAT_GPIO_API_LIGHTING_LCD
#define CONFIG_MOT_FEAT_GPIO_API_LIGHTING_CAM_TORCH 1
#define CONFIG_MOT_FEAT_GPIO_API_LIGHTING_CAM_FLASH 1
#define CONFIG_MOT_FEAT_GPIO_API_LIGHTING_EL 1

/*
 * End of Motorola GPIO Lighting API
 */
#define CONFIG_MOT_FEAT_GPIO_API_MMCSD 1
#undef CONFIG_MOT_FEAT_GPIO_API_SDHC
#define CONFIG_MOT_FEAT_GPIO_API_SERIALIZER 1
#define CONFIG_MOT_FEAT_GPIO_API_USBHS 1
#undef CONFIG_MOT_FEAT_GPIO_API_WLAN

/*
 * End of Motorola-hardware-specific GPIO API
 */
#define CONFIG_MOT_WFN414 1
#define CONFIG_MOT_WFN431 1
#define CONFIG_MOT_WFN424 1
#define CONFIG_MOT_WFN420 1
#define CONFIG_MOT_WFN419 1
#define CONFIG_MOT_WFN452 1
#define CONFIG_MOT_FEAT_YAFFS_PARSE_MOUNT_OPTIONS 1
#define CONFIG_MOT_FEAT_YAFFS_SHREDDER 1
#define CONFIG_MOT_WFN440 1
#define CONFIG_MOT_WFN436 1
#define CONFIG_MOT_WFN446 1
#define CONFIG_MOT_WFN453 1
#define CONFIG_MOT_WFN441 1
#define CONFIG_MOT_WFN443 1
#define CONFIG_MOT_FEAT_2MP_CAMERA_WRKARND 1
#define CONFIG_MOT_WFN444 1
#define CONFIG_MOT_WFN389 1
#undef CONFIG_MOT_FEAT_STM90NM
#define CONFIG_MOT_WFN421 1
#define CONFIG_MOT_WFN454 1
#undef CONFIG_MOT_WFN455
#define CONFIG_MOT_WFN457 1
#undef CONFIG_MOT_FEAT_INTERN_SD
#define CONFIG_MOT_FEAT_EXTERN_SD 1
#undef CONFIG_MOT_FEAT_MEGASIM
#define CONFIG_MOT_WFN445 1
#undef CONFIG_MOT_FEAT_MMCSD_DEV_HOST_BIND
#define CONFIG_MOT_WFN458 1
#define CONFIG_MOT_WFN456 1
#define CONFIG_MOT_WFN461 1
#define CONFIG_MOT_WFN462 1
#define CONFIG_MOT_WFN465 1
#undef CONFIG_MOT_FEAT_VFP_RUNFAST_PANIC
#define CONFIG_MOT_FEAT_NO_PAGE_SHARED 1
#undef CONFIG_MOT_FEAT_SYNC_INODE
#define CONFIG_MOT_WFN472 1
#define CONFIG_MOT_WFN473 1
#define CONFIG_MOT_WFN475 1
#define CONFIG_MOT_WFN476 1
#define CONFIG_MOT_WFN479 1
#define CONFIG_MOT_FEAT_HOTPLUG_FILTER 1
#define CONFIG_MOT_FEAT_NO_READ_AHEAD 1
#define CONFIG_MOT_WFN477 1
#define CONFIG_MOT_FEAT_PRINT_PC_ON_PANIC 1
#define CONFIG_MOT_FEAT_PANIC_ON_OOM 1
#define CONFIG_MOT_WFN482 1

/*
 * End of Motorola Features and Bug Fixes
 */
#define CONFIG_ARM 1
#define CONFIG_MMU 1
#define CONFIG_UID16 1
#define CONFIG_GENERIC_IOMAP 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_BROKEN_ON_SMP 1
#define CONFIG_LOCK_KERNEL 1

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#undef CONFIG_SWAP
#define CONFIG_SYSVIPC 1
#define CONFIG_SYSVIPC_SEMMNI 128
#define CONFIG_SYSVIPC_SEMMSL 250
#define CONFIG_POSIX_MQUEUE 1
#undef CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#undef CONFIG_AUDIT
#define CONFIG_LOG_BUF_SHIFT 14
#define CONFIG_HOTPLUG 1
#define CONFIG_KOBJECT_UEVENT 1
#undef CONFIG_IKCONFIG
#define CONFIG_EMBEDDED 1
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_ALL
#undef CONFIG_KALLSYMS_EXTRA_PASS
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_CC_OPTIMIZE_FOR_SIZE 1
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#undef CONFIG_LTT
#define CONFIG_LTT_MAX_HANDLES 128
#undef CONFIG_BOOT_FLIGHT_RECORDER
#define CONFIG_LOCKLESS 1
#define CONFIG_BOOT_FLIGHT_BUFFERS 4
#define CONFIG_BOOT_FLIGHT_SIZE 524288
#define CONFIG_FLIGHT_PROC_BUFFERS 8
#define CONFIG_FLIGHT_PROC_SIZE 8192
#define CONFIG_NEWEV 1
#define CONFIG_CSTM 1
#undef CONFIG_GPIO
#undef CONFIG_TINY_SHMEM

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#define CONFIG_MODULE_FORCE_UNLOAD 1
#define CONFIG_OBSOLETE_MODPARM 1
#define CONFIG_MODVERSIONS 1
#undef CONFIG_MODULE_SRCVERSION_ALL
#define CONFIG_KMOD 1
#define CONFIG_SUAPI 1

/*
 * System type and features
 */
#undef CONFIG_ARCH_CLPS7500
#undef CONFIG_ARCH_CLPS711X
#undef CONFIG_ARCH_CO285
#undef CONFIG_ARCH_EBSA110
#undef CONFIG_ARCH_CAMELOT
#undef CONFIG_ARCH_FOOTBRIDGE
#undef CONFIG_ARCH_INTEGRATOR
#define CONFIG_ARCH_MXC 1
#undef CONFIG_ARCH_IOP3XX
#undef CONFIG_ARCH_IXP4XX
#undef CONFIG_ARCH_IXP2000
#undef CONFIG_ARCH_L7200
#undef CONFIG_ARCH_PXA
#undef CONFIG_ARCH_RPC
#undef CONFIG_ARCH_SA1100
#undef CONFIG_ARCH_S3C2410
#undef CONFIG_ARCH_SHARK
#undef CONFIG_ARCH_LH7A40X
#undef CONFIG_ARCH_OMAP
#undef CONFIG_ARCH_VERSATILE
#undef CONFIG_ARCH_IMX
#undef CONFIG_ARCH_H720X
#undef CONFIG_ARCH_PNX4008

/*
 * Freescale MXC Implementations
 */
#undef CONFIG_ARCH_MXC91331
#undef CONFIG_ARCH_MXC91321
#define CONFIG_ARCH_MXC91231 1
#undef CONFIG_ARCH_MXC91131
#undef CONFIG_ARCH_MX3

/*
 * MXC91231 Options
 */
#undef CONFIG_MACH_MXC27530EVB
#undef CONFIG_MACH_SCMA11REF
#define CONFIG_MACH_ASCENSION 1
#undef CONFIG_MACH_LIDO
#undef CONFIG_MACH_SAIPAN
#undef CONFIG_MACH_ELBA
#undef CONFIG_MACH_PICO
#define CONFIG_MXC_DSP_BRINGUP 1

/*
 * Processor Type
 */
#define CONFIG_CPU_32 1
#define CONFIG_CPU_V6 1
#define CONFIG_CPU_32v6 1
#define CONFIG_CPU_ABRT_EV6 1
#define CONFIG_CPU_CACHE_V6 1
#define CONFIG_CPU_CACHE_VIPT 1
#define CONFIG_CPU_CACHE_L210 1
#define CONFIG_CPU_COPY_V6 1
#define CONFIG_CPU_TLB_V6 1
#define CONFIG_CPU_L210CACHE 1

/*
 * Processor Features
 */
#define CONFIG_ARM_THUMB 1
#define CONFIG_AEABI 1
#define CONFIG_OABI_COMPAT 1
#undef CONFIG_DISCONTIGMEM
#define CONFIG_ISA 1
#define CONFIG_ZBOOT_ROM_TEXT 0x0
#define CONFIG_ZBOOT_ROM_BSS 0x0
#undef CONFIG_XIP_KERNEL
#define CONFIG_HIGH_RES_TIMERS 1
#undef CONFIG_VST
#undef CONFIG_IDLE
#undef CONFIG_CPU_FREQ

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#undef CONFIG_PCCARD

/*
 * PC-card bridges
 */
#define CONFIG_PCMCIA_PROBE 1

/*
 * At least one math emulation must be selected
 */
#undef CONFIG_FPE_NWFPE
#undef CONFIG_FPE_FASTFPE
#define CONFIG_VFP 1
#define CONFIG_BINFMT_ELF 1
#undef CONFIG_BINFMT_AOUT
#undef CONFIG_BINFMT_MISC
#undef CONFIG_PREEMPT_NONE
#undef CONFIG_PREEMPT_VOLUNTARY
#define CONFIG_PREEMPT_DESKTOP 1
#undef CONFIG_PREEMPT_RT
#define CONFIG_PREEMPT 1
#undef CONFIG_PREEMPT_SOFTIRQS
#undef CONFIG_PREEMPT_HARDIRQS
#undef CONFIG_PREEMPT_RCU
#undef CONFIG_SPINLOCK_BKL
#define CONFIG_PREEMPT_BKL 1
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#define CONFIG_ASM_SEMAPHORES 1

/*
 * Power management options (PM, DPM, ACPI, APM)
 */
#define CONFIG_PM 1
#undef CONFIG_APM
#undef CONFIG_SUSPEND_REMOUNTFS

/*
 * Dynamic Power Management
 */
#undef CONFIG_DPM

/*
 * Event Broker
 */
#undef CONFIG_EVENT_BROKER
#define CONFIG_CMDLINE ""
#define CONFIG_ALIGNMENT_TRAP 1

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#define CONFIG_STANDALONE 1
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#undef CONFIG_FW_LOADER
#undef CONFIG_DEBUG_DRIVER

/*
 * Parallel port support
 */
#undef CONFIG_PARPORT

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD 1
#undef CONFIG_MTD_DEBUG
#undef CONFIG_MTD_CONCAT
#define CONFIG_MTD_PARTITIONS 1
#undef CONFIG_MTD_REDBOOT_PARTS
#define CONFIG_MTD_CMDLINE_PARTS 1
#undef CONFIG_MTD_AFS_PARTS

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR 1
#define CONFIG_MTD_BLOCK 1
#undef CONFIG_FTL
#undef CONFIG_NFTL
#undef CONFIG_INFTL
#undef CONFIG_RFD_FTL

/*
 * RAM/ROM/Flash chip drivers
 */
#undef CONFIG_MTD_CFI
#undef CONFIG_MTD_JEDECPROBE
#define CONFIG_MTD_MAP_BANK_WIDTH_1 1
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
#define CONFIG_MTD_MAP_BANK_WIDTH_4 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_8
#undef CONFIG_MTD_MAP_BANK_WIDTH_16
#undef CONFIG_MTD_MAP_BANK_WIDTH_32
#define CONFIG_MTD_CFI_I1 1
#define CONFIG_MTD_CFI_I2 1
#undef CONFIG_MTD_CFI_I4
#undef CONFIG_MTD_CFI_I8
#define CONFIG_MTD_RAM 1
#undef CONFIG_MTD_ROM
#undef CONFIG_MTD_ABSENT

/*
 * Mapping drivers for chip access
 */
#undef CONFIG_MTD_COMPLEX_MAPPINGS
#undef CONFIG_MTD_PLATRAM
#undef CONFIG_MTD_MXC

/*
 * Self-contained MTD device drivers
 */
#undef CONFIG_MTD_SLRAM
#undef CONFIG_MTD_PHRAM
#undef CONFIG_MTD_MTDRAM
#undef CONFIG_RAMTD
#undef CONFIG_MTD_BLKMTD
#undef CONFIG_MTD_BLOCK2MTD

/*
 * Disk-On-Chip Device Drivers
 */
#undef CONFIG_MTD_DOC2000
#undef CONFIG_MTD_DOC2001
#undef CONFIG_MTD_DOC2001PLUS

/*
 * NAND Flash Device Drivers
 */
#define CONFIG_MTD_NAND 1
#undef CONFIG_MTD_NAND_VERIFY_WRITE
#define CONFIG_MTD_NAND_IDS 1
#undef CONFIG_MTD_NAND_DISKONCHIP
#undef CONFIG_MTD_NAND_NANDSIM
#define CONFIG_MTD_NAND_MXC 1
#undef CONFIG_MTD_NAND_MXC_SWECC
#undef CONFIG_MTD_NAND_MXC_FORCE_CE
#undef CONFIG_MTD_NAND_MXC_ECC_CORRECTION_OPTION2
#undef CONFIG_CONFIG_MXC_NAND_LOW_LEVEL_ERASE
#define CONFIG_MTD_NAND_BBM 1
#undef CONFIG_MTD_NAND_BBM_DBG

/*
 * OneNAND Flash Device Drivers
 */
#undef CONFIG_MTD_ONENAND

/*
 * Plug and Play support
 */
#undef CONFIG_PNP

/*
 * Block devices
 */
#undef CONFIG_BLK_DEV_FD
#undef CONFIG_BLK_DEV_XD
#define CONFIG_BLK_DEV_LOOP 1
#undef CONFIG_BLK_DEV_CRYPTOLOOP
#undef CONFIG_BLK_DEV_NBD
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_COUNT 16
#define CONFIG_BLK_DEV_RAM_SIZE 16384
#undef CONFIG_BLK_DEV_INITRD
#define CONFIG_INITRAMFS_SOURCE ""
#undef CONFIG_CDROM_PKTCDVD

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1

/*
 * Multi-device support (RAID and LVM)
 */
#undef CONFIG_MD

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#undef CONFIG_NETLINK_DEV
#define CONFIG_UNIX 1
#undef CONFIG_NET_KEY
#define CONFIG_USE_POLICY_FWD 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#undef CONFIG_IP_ROUTE_FWMARK
#undef CONFIG_IP_ROUTE_MULTIPATH
#undef CONFIG_IP_ROUTE_VERBOSE
#define CONFIG_IP_PNP 1
#define CONFIG_IP_PNP_DHCP 1
#undef CONFIG_IP_PNP_BOOTP
#undef CONFIG_IP_PNP_RARP
#undef CONFIG_NET_IPIP
#undef CONFIG_NET_IPGRE
#undef CONFIG_IP_MROUTE
#undef CONFIG_ARPD
#undef CONFIG_SYN_COOKIES
#undef CONFIG_INET_AH
#undef CONFIG_INET_ESP
#undef CONFIG_INET_IPCOMP
#undef CONFIG_INET_TUNNEL
#define CONFIG_IP_TCPDIAG 1
#undef CONFIG_IP_TCPDIAG_IPV6

/*
 * IP: Virtual Server Configuration
 */
#undef CONFIG_IP_VS
#undef CONFIG_IPV6
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK 1
#undef CONFIG_IP_NF_CT_ACCT
#undef CONFIG_IP_NF_CONNTRACK_MARK
#undef CONFIG_IP_NF_CT_PROTO_SCTP
#define CONFIG_IP_NF_FTP 1
#undef CONFIG_IP_NF_IRC
#undef CONFIG_IP_NF_TFTP
#undef CONFIG_IP_NF_AMANDA
#undef CONFIG_IP_NF_QUEUE
#define CONFIG_IP_NF_IPTABLES 1
#undef CONFIG_IP_NF_MATCH_LIMIT
#define CONFIG_IP_NF_MATCH_IPRANGE 1
#undef CONFIG_IP_NF_MATCH_MAC
#undef CONFIG_IP_NF_MATCH_PKTTYPE
#undef CONFIG_IP_NF_MATCH_MARK
#undef CONFIG_IP_NF_MATCH_MULTIPORT
#undef CONFIG_IP_NF_MATCH_TOS
#undef CONFIG_IP_NF_MATCH_RECENT
#undef CONFIG_IP_NF_MATCH_ECN
#undef CONFIG_IP_NF_MATCH_DSCP
#undef CONFIG_IP_NF_MATCH_AH_ESP
#undef CONFIG_IP_NF_MATCH_LENGTH
#undef CONFIG_IP_NF_MATCH_TTL
#undef CONFIG_IP_NF_MATCH_TCPMSS
#undef CONFIG_IP_NF_MATCH_HELPER
#define CONFIG_IP_NF_MATCH_STATE 1
#undef CONFIG_IP_NF_MATCH_CONNTRACK
#undef CONFIG_IP_NF_MATCH_OWNER
#undef CONFIG_IP_NF_MATCH_ADDRTYPE
#undef CONFIG_IP_NF_MATCH_REALM
#undef CONFIG_IP_NF_MATCH_SCTP
#undef CONFIG_IP_NF_MATCH_COMMENT
#undef CONFIG_IP_NF_MATCH_HASHLIMIT
#define CONFIG_IP_NF_FILTER 1
#define CONFIG_IP_NF_TARGET_REJECT 1
#define CONFIG_IP_NF_TARGET_LOG 1
#define CONFIG_IP_NF_TARGET_ULOG 1
#undef CONFIG_IP_NF_TARGET_TCPMSS
#undef CONFIG_IP_NF_NAT
#undef CONFIG_IP_NF_MANGLE
#undef CONFIG_IP_NF_RAW
#undef CONFIG_IP_NF_ARPTABLES

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#undef CONFIG_IP_SCTP
#undef CONFIG_ATM
#undef CONFIG_BRIDGE
#undef CONFIG_VLAN_8021Q
#undef CONFIG_DECNET
#undef CONFIG_LLC2
#undef CONFIG_IPX
#undef CONFIG_ATALK
#undef CONFIG_X25
#undef CONFIG_LAPB
#undef CONFIG_NET_DIVERT
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER

/*
 * QoS and/or fair queueing
 */
#undef CONFIG_NET_SCHED
#undef CONFIG_NET_CLS_ROUTE

/*
 * Network testing
 */
#undef CONFIG_NET_PKTGEN
#undef CONFIG_NETPOLL
#undef CONFIG_NET_POLL_CONTROLLER
#undef CONFIG_HAMRADIO
#undef CONFIG_IRDA
#define CONFIG_BT_MODULE 1
#define CONFIG_BT_L2CAP_MODULE 1
#define CONFIG_BT_SCO_MODULE 1
#define CONFIG_BT_RFCOMM_MODULE 1
#define CONFIG_BT_RFCOMM_TTY 1
#define CONFIG_BT_BNEP_MODULE 1
#define CONFIG_BT_BNEP_MC_FILTER 1
#define CONFIG_BT_BNEP_PROTO_FILTER 1
#define CONFIG_BT_HIDP_MODULE 1

/*
 * Bluetooth device drivers
 */
#define CONFIG_BT_HCIUART_MODULE 1
#define CONFIG_BT_HCIUART_H4 1
#define CONFIG_BT_HCIUART_BCSP 1
#define CONFIG_BT_HCIUART_BCSP_TXCRC 1
#define CONFIG_BT_HCIVHCI_MODULE 1
#undef CONFIG_IEEE80211
#define CONFIG_NETDEVICES 1
#undef CONFIG_DUMMY
#undef CONFIG_BONDING
#undef CONFIG_EQUALIZER
#undef CONFIG_TUN

/*
 * ARCnet devices
 */
#undef CONFIG_ARCNET

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII 1
#undef CONFIG_NET_VENDOR_3COM
#undef CONFIG_LANCE
#undef CONFIG_NET_VENDOR_SMC
#undef CONFIG_SMC91X
#undef CONFIG_NET_VENDOR_RACAL
#undef CONFIG_AT1700
#undef CONFIG_DEPCA
#undef CONFIG_HP100
#undef CONFIG_NET_ISA
#define CONFIG_NET_PCI 1
#undef CONFIG_AC3200
#undef CONFIG_APRICOT
#undef CONFIG_CS89x0
#undef CONFIG_NET_POCKET

/*
 * Ethernet (1000 Mbit)
 */

/*
 * Ethernet (10000 Mbit)
 */

/*
 * Token Ring devices
 */
#undef CONFIG_TR

/*
 * Wireless LAN (non-hamradio)
 */
#undef CONFIG_NET_RADIO

/*
 * Wan interfaces
 */
#undef CONFIG_WAN
#define CONFIG_PPP 1
#undef CONFIG_PPP_MULTILINK
#undef CONFIG_PPP_FILTER
#define CONFIG_PPP_ASYNC 1
#define CONFIG_PPP_SYNC_TTY 1
#undef CONFIG_PPP_DEFLATE
#undef CONFIG_PPP_BSDCOMP
#undef CONFIG_PPPOE
#define CONFIG_SLIP 1
#undef CONFIG_SLIP_COMPRESSED
#undef CONFIG_SLIP_SMART
#undef CONFIG_SLIP_MODE_SLIP6
#undef CONFIG_SHAPER
#undef CONFIG_NETCONSOLE

/*
 * SCSI device support
 */
#undef CONFIG_SCSI

/*
 * Fusion MPT device support
 */

/*
 * IEEE 1394 (FireWire) support
 */

/*
 * I2O device support
 */

/*
 * ISDN subsystem
 */
#undef CONFIG_ISDN

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#undef CONFIG_INPUT_MOUSEDEV
#undef CONFIG_INPUT_JOYDEV
#undef CONFIG_INPUT_TSDEV
#undef CONFIG_INPUT_TSLIBDEV
#define CONFIG_INPUT_EVDEV 1
#undef CONFIG_INPUT_EVBUG

/*
 * Input I/O drivers
 */
#undef CONFIG_GAMEPORT
#define CONFIG_SOUND_GAMEPORT 1
#undef CONFIG_SERIO

/*
 * Input Device Drivers
 */
#undef CONFIG_INPUT_KEYBOARD
#undef CONFIG_INPUT_MOUSE
#undef CONFIG_INPUT_JOYSTICK
#undef CONFIG_INPUT_TOUCHSCREEN
#undef CONFIG_INPUT_MISC

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#undef CONFIG_SERIAL_NONSTANDARD
#define CONFIG_MXC_MU 1
#define CONFIG_MXC_IPC 1
#undef CONFIG_MXC_SDMA_TTY
#define CONFIG_MXC_RTC 1

/*
 * Serial drivers
 */
#undef CONFIG_SERIAL_8250

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_MXC 1
#define CONFIG_SERIAL_MXC_CONSOLE 1
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#define CONFIG_MOT_FEAT_SERIAL 1
#define CONFIG_UNIX98_PTYS 1
#undef CONFIG_LEGACY_PTYS

/*
 * IPMI
 */
#undef CONFIG_IPMI_HANDLER

/*
 * Watchdog Cards
 */
#undef CONFIG_WATCHDOG
#undef CONFIG_NVRAM
#undef CONFIG_RTC
#undef CONFIG_BLOCKER
#undef CONFIG_DTLK
#undef CONFIG_R3964

/*
 * Ftape, the floppy tape device driver
 */
#undef CONFIG_DRM
#undef CONFIG_RAW_DRIVER
#undef CONFIG_FUSION_DEVICE

/*
 * I2C support
 */
#define CONFIG_I2C 1
#undef CONFIG_I2C_CHARDEV

/*
 * I2C Algorithms
 */
#undef CONFIG_I2C_ALGOBIT
#undef CONFIG_I2C_ALGOPCF
#undef CONFIG_I2C_ALGOPCA
#undef CONFIG_I2C_ALGO_SGI

/*
 * I2C Hardware Bus support
 */
#undef CONFIG_I2C_ELEKTOR
#undef CONFIG_I2C_ISA
#define CONFIG_I2C_MXC 1
#undef CONFIG_I2C_PARPORT_LIGHT
#undef CONFIG_I2C_STUB
#undef CONFIG_I2C_PCA_ISA
#undef CONFIG_I2C_OMAP

/*
 * Hardware Sensors Chip support
 */
#define CONFIG_I2C_SENSOR 1
#undef CONFIG_SENSORS_ADM1021
#undef CONFIG_SENSORS_ADM1025
#undef CONFIG_SENSORS_ADM1026
#undef CONFIG_SENSORS_ADM1031
#undef CONFIG_SENSORS_ASB100
#undef CONFIG_SENSORS_DS1621
#undef CONFIG_SENSORS_FSCHER
#undef CONFIG_SENSORS_GL518SM
#undef CONFIG_SENSORS_IT87
#undef CONFIG_SENSORS_LM63
#undef CONFIG_SENSORS_LM75
#undef CONFIG_SENSORS_LM77
#undef CONFIG_SENSORS_LM78
#undef CONFIG_SENSORS_LM80
#undef CONFIG_SENSORS_LM83
#undef CONFIG_SENSORS_LM85
#undef CONFIG_SENSORS_LM87
#undef CONFIG_SENSORS_LM90
#undef CONFIG_SENSORS_MAX1619
#undef CONFIG_SENSORS_PC87360
#undef CONFIG_SENSORS_SMSC47M1
#undef CONFIG_SENSORS_W83781D
#define CONFIG_MXC_I2C_CLIENT 1
#undef CONFIG_SENSORS_W83L785TS
#undef CONFIG_SENSORS_W83627HF

/*
 * Other I2C Chip support
 */
#undef CONFIG_SENSORS_EEPROM
#undef CONFIG_SENSORS_PCF8574
#undef CONFIG_SENSORS_PCF8591
#undef CONFIG_SENSORS_RTC8564
#undef CONFIG_TPS65010
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * SPI support
 */
#undef CONFIG_SPI
#undef CONFIG_SPI_MASTER

/*
 * Dallas's 1-wire bus
 */
#undef CONFIG_W1

/*
 * File systems
 */
#undef CONFIG_EXT2_FS
#undef CONFIG_EXT3_FS
#undef CONFIG_JBD
#undef CONFIG_REISERFS_FS
#undef CONFIG_JFS_FS
#undef CONFIG_XFS_FS
#undef CONFIG_MINIX_FS
#undef CONFIG_ROMFS_FS
#undef CONFIG_QUOTA
#define CONFIG_DNOTIFY 1
#undef CONFIG_AUTOFS_FS
#undef CONFIG_AUTOFS4_FS

/*
 * CD-ROM/DVD Filesystems
 */
#undef CONFIG_ISO9660_FS
#undef CONFIG_UDF_FS

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS 1
#undef CONFIG_MSDOS_FS
#define CONFIG_VFAT_FS 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#undef CONFIG_NTFS_FS

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_SYSFS 1
#define CONFIG_DEVFS_FS 1
#define CONFIG_DEVFS_MOUNT 1
#undef CONFIG_DEVFS_DEBUG
#undef CONFIG_DEVPTS_FS_XATTR
#define CONFIG_TMPFS 1
#undef CONFIG_TMPFS_XATTR
#undef CONFIG_HUGETLB_PAGE
#define CONFIG_RAMFS 1
#define CONFIG_RELAYFS_FS 1
#undef CONFIG_KLOG_CHANNEL

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#undef CONFIG_AFFS_FS
#undef CONFIG_HFS_FS
#undef CONFIG_HFSPLUS_FS
#undef CONFIG_BEFS_FS
#undef CONFIG_BFS_FS
#undef CONFIG_EFS_FS
#undef CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS 1
#define CONFIG_JFFS2_FS_DEBUG 0
#define CONFIG_JFFS2_FS_WRITEBUFFER 1
#undef CONFIG_JFFS2_COMPRESSION_OPTIONS
#define CONFIG_JFFS2_ZLIB 1
#define CONFIG_JFFS2_RTIME 1
#undef CONFIG_JFFS2_RUBIN
#define CONFIG_CRAMFS 1
#undef CONFIG_CRAMFS_LINEAR
#define CONFIG_SQUASHFS 1
#define CONFIG_SQUASHFS_EMBEDDED 1
#define CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE 3
#define CONFIG_SQUASHFS_VMALLOC 1
#undef CONFIG_VXFS_FS
#undef CONFIG_HPFS_FS
#undef CONFIG_PRAMFS
#undef CONFIG_QNX4FS_FS
#undef CONFIG_SYSV_FS
#undef CONFIG_UFS_FS
#define CONFIG_YAFFS_FS 1
#define CONFIG_YAFFS_YAFFS1 1
#undef CONFIG_YAFFS_DOES_ECC
#define CONFIG_YAFFS_YAFFS2 1
#define CONFIG_YAFFS_DISABLE_CHUNK_ERASED_CHECK 1
#define CONFIG_YAFFS_SHORT_NAMES_IN_RAM 1
#define CONFIG_YAFFS_MXC_MODE 1
#undef CONFIG_YAFFS1_FS
#undef CONFIG_YAFFS2_FS_LP
#undef CONFIG_YAFFS_AUTO_YAFFS2
#undef CONFIG_YAFFS_DISABLE_LAZY_LOAD

/*
 * Network File Systems
 */
#undef CONFIG_NFS_FS
#undef CONFIG_NFSD
#undef CONFIG_EXPORTFS
#undef CONFIG_SMB_FS
#undef CONFIG_CIFS
#undef CONFIG_NCP_FS
#undef CONFIG_CODA_FS
#undef CONFIG_AFS_FS

/*
 * Partition Types
 */
#undef CONFIG_PARTITION_ADVANCED
#define CONFIG_MSDOS_PARTITION 1

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "iso8859-1"
#define CONFIG_NLS_CODEPAGE_437 1
#undef CONFIG_NLS_CODEPAGE_737
#undef CONFIG_NLS_CODEPAGE_775
#undef CONFIG_NLS_CODEPAGE_850
#undef CONFIG_NLS_CODEPAGE_852
#undef CONFIG_NLS_CODEPAGE_855
#undef CONFIG_NLS_CODEPAGE_857
#undef CONFIG_NLS_CODEPAGE_860
#undef CONFIG_NLS_CODEPAGE_861
#undef CONFIG_NLS_CODEPAGE_862
#undef CONFIG_NLS_CODEPAGE_863
#undef CONFIG_NLS_CODEPAGE_864
#undef CONFIG_NLS_CODEPAGE_865
#undef CONFIG_NLS_CODEPAGE_866
#undef CONFIG_NLS_CODEPAGE_869
#undef CONFIG_NLS_CODEPAGE_936
#undef CONFIG_NLS_CODEPAGE_950
#undef CONFIG_NLS_CODEPAGE_932
#undef CONFIG_NLS_CODEPAGE_949
#undef CONFIG_NLS_CODEPAGE_874
#undef CONFIG_NLS_ISO8859_8
#undef CONFIG_NLS_CODEPAGE_1250
#undef CONFIG_NLS_CODEPAGE_1251
#undef CONFIG_NLS_ASCII
#define CONFIG_NLS_ISO8859_1 1
#undef CONFIG_NLS_ISO8859_2
#undef CONFIG_NLS_ISO8859_3
#undef CONFIG_NLS_ISO8859_4
#undef CONFIG_NLS_ISO8859_5
#undef CONFIG_NLS_ISO8859_6
#undef CONFIG_NLS_ISO8859_7
#undef CONFIG_NLS_ISO8859_9
#undef CONFIG_NLS_ISO8859_13
#undef CONFIG_NLS_ISO8859_14
#undef CONFIG_NLS_ISO8859_15
#undef CONFIG_NLS_KOI8_R
#undef CONFIG_NLS_KOI8_U
#define CONFIG_NLS_UTF8 1

/*
 * Profiling support
 */
#undef CONFIG_PROFILING

/*
 * Graphics support
 */
#define CONFIG_FB 1
#undef CONFIG_FB_MODE_HELPERS
#define CONFIG_FB_TILEBLITTING 1
#define CONFIG_FB_MXC 1
#undef CONFIG_FB_MXC_16BPP
#define CONFIG_FB_MXC_24BPP 1
#undef CONFIG_FB_MXC_32BPP
#define CONFIG_FB_MXC_SYNC_PANEL 1
#define CONFIG_FB_MXC_SANYO_QVGA_PANEL 1
#undef CONFIG_FB_MXC_SHARP_QVGA_PANEL
#undef CONFIG_FB_MXC_VGA_PANEL
#undef CONFIG_FB_MXC_TVOUT
#define CONFIG_FB_MXC_OVERLAY 1
#define CONFIG_FB_MXC_INTERNAL_MEM 1
#undef CONFIG_FB_MXC_ASYNC_PANEL
#undef CONFIG_FB_MXC_SYNC_ASYNC_PANEL
#define CONFIG_FB_MXC_MAIN_TRANSMISSIVE_DISPLAY 1
#undef CONFIG_FB_MXC_MAIN_TRANSFLECTIVE_DISPLAY
#undef CONFIG_FB_MXC_CLI_TRANSMISSIVE_DISPLAY
#define CONFIG_FB_MXC_CLI_TRANSFLECTIVE_DISPLAY 1
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#undef CONFIG_VGA_CONSOLE
#undef CONFIG_MDA_CONSOLE
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#undef CONFIG_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1

/*
 * Logo configuration
 */
#undef CONFIG_LOGO

/*
 * Multimedia devices
 */
#define CONFIG_VIDEO_DEV 1

/*
 * Video For Linux
 */

/*
 * Video Adapters
 */
#undef CONFIG_VIDEO_PMS
#define CONFIG_VIDEO_MXC_CAMERA 1

/*
 * MXC Camera/V4L2 PRP Features support
 */
#undef CONFIG_MXC_CAMERA_MICRON111
#define CONFIG_MXC_IPU_CAMERA_SENSOR2M 1
#define CONFIG_MXC_IPU_PRP_VF_SDC 1
#define CONFIG_MXC_IPU_PRP_ENC 1
#define CONFIG_MXC_IPU_CAMERA_I2C_INTERFACE 1
#define CONFIG_VIDEO_MXC_OUTPUT 1
#define CONFIG_VIDEO_MXC_V4L1 1
#undef CONFIG_VIDEO_CPIA
#undef CONFIG_VIDEO_SAA5246A
#undef CONFIG_VIDEO_SAA5249
#undef CONFIG_TUNER_3036
#undef CONFIG_VIDEO_OVCAMCHIP

/*
 * Radio Adapters
 */
#undef CONFIG_RADIO_CADET
#undef CONFIG_RADIO_RTRACK
#undef CONFIG_RADIO_RTRACK2
#undef CONFIG_RADIO_AZTECH
#undef CONFIG_RADIO_GEMTEK
#undef CONFIG_RADIO_MAESTRO
#undef CONFIG_RADIO_SF16FMI
#undef CONFIG_RADIO_SF16FMR2
#undef CONFIG_RADIO_TERRATEC
#undef CONFIG_RADIO_TRUST
#undef CONFIG_RADIO_TYPHOON
#undef CONFIG_RADIO_ZOLTRIX

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB

/*
 * Sound
 */
#undef CONFIG_SOUND

/*
 * Misc devices
 */

/*
 * Multimedia Capabilities Port drivers
 */

/*
 * USB support
 */
#undef CONFIG_USB
#define CONFIG_USB_ARCH_HAS_HCD 1
#undef CONFIG_USB_ARCH_HAS_OHCI

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support' may also be needed; see USB_STORAGE Help for more information
 */

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * On-The-Go and USB Peripheral Support
 */
#define CONFIG_OTG_MODULE 1
#define CONFIG_OTG_HIGH_SPEED 1
#undef CONFIG_OTG_NFS

/*
 * 
 */

/*
 * On-The-Go Support Platform Selection
 */
#define CONFIG_OTG_BRASSBOARD_MODULE 1
#define CONFIG_OTG_BRASSBOARD_ISP1104 1
#undef CONFIG_OTG_BRASSBOARD_MC13783
#define CONFIG_OTG_BRASSBOARD_DIFFERENTIAL_UNIDIRECTIONAL 1
#undef CONFIG_OTG_BRASSBOARD_DIFFERENTIAL_BIDIRECTIONAL
#undef CONFIG_OTG_BRASSBOARD_SINGLE_ENDED_UNIDIRECTIONAL
#undef CONFIG_OTG_BRASSBOARD_SINGLE_ENDED_BIDIRECTIONAL
#define CONFIG_OTG_HRT 1
#define CONFIG_OTG_PLATFORM_OTG 1
#define CONFIG_OTG_PLATFORM_USB 1
#define CONFIG_OTG_PLATFORM_USBD 1
#define CONFIG_OTG_FREESCALE 1

/*
 * 
 */

/*
 * On-The-Go Options
 */
#define CONFIG_OTG_USB_PERIPHERAL 1
#undef CONFIG_OTG_USB_PERIPHERAL_OR_HOST
#undef CONFIG_OTG_DEVICE
#undef CONFIG_OTG_TR_AUTO

/*
 * 
 */

/*
 * OTG Support In Linux USB Core
 */

/*
 * 
 */

/*
 * Language
 */
#define CONFIG_OTG_LANGID 0x0904

/*
 * Testing and Portability
 */
#undef CONFIG_OTG_TRACE
#undef CONFIG_OTG_NOC99

/*
 * Targeted Peripherals List (USB Peripheral Function Drivers)
 */

/*
 * OTG Generic function
 */
#define CONFIG_OTG_GENERIC_MODULE 1
#define CONFIG_OTG_GENERIC_HOTPLUG 1

/*
 * OTG Generic Composite function options
 */
#define CONFIG_OTG_GENERIC_VENDORID 0x22b8
#define CONFIG_OTG_GENERIC_PRODUCTID 0x6424
#define CONFIG_OTG_GENERIC_BCDDEVICE 0x0101
#define CONFIG_OTG_GENERIC_MANUFACTURER "Motorola Inc."
#define CONFIG_OTG_GENERIC_PRODUCT_NAME "Motorola USB Device"
#define CONFIG_OTG_ACM_NETWORK_PRODUCTID 0x6425
#define CONFIG_OTG_ACM_NETWORK_BLAN_DESC "Motorola ACM BLAN Configuration"
#define CONFIG_OTG_GENERIC_CONFIG_NONE 1
#undef CONFIG_OTG_GENERIC_CONFIG_MOUSE
#undef CONFIG_OTG_GENERIC_CONFIG_NET_BLAN
#undef CONFIG_OTG_GENERIC_CONFIG_NET_CDC
#undef CONFIG_OTG_GENERIC_CONFIG_NET_SAFE
#undef CONFIG_OTG_GENERIC_CONFIG_ACM_TTY
#undef CONFIG_OTG_GENERIC_CONFIG_MSC
#undef CONFIG_OTG_GENERIC_CONFIG_MTP
#undef CONFIG_OTG_GENERIC_CONFIG_PBG
#undef CONFIG_OTG_GENERIC_CONFIG_MOUSE2
#undef CONFIG_OTG_GENERIC_CONFIG_MSC_MOUSE
#undef CONFIG_OTG_GENERIC_CONFIG_MOUSE_BLAN
#undef CONFIG_OTG_GENERIC_CONFIG_MSC_BLAN
#undef CONFIG_OTG_GENERIC_CONFIG_MSC_CDC
#define CONFIG_OTG_GENERIC_CONFIG_NAME ""

/*
 * OTG ACM Function
 */
#define CONFIG_OTG_ACM_MODULE 1

/*
 * OTG ACM function options
 */
#define CONFIG_OTG_ACM_VENDORID 0x22b8
#define CONFIG_OTG_ACM_PRODUCTID 0x6422
#define CONFIG_OTG_ACM_BCDDEVICE 0x0101
#define CONFIG_OTG_ACM_MANUFACTURER "Motorola Inc."
#define CONFIG_OTG_ACM_PRODUCT_NAME "Motorola USB device"
#define CONFIG_OTG_ACM_DESC "Motorola Communication Class"
#define CONFIG_OTG_ACM_HOTPLUG 1
#define CONFIG_OTG_ACM_COMM_INTF "Motorola Communication Interface"
#define CONFIG_OTG_ACM_NODATA_INTF "Motorola Data Interface"
#define CONFIG_OTG_ACM_DATA_INTF "Motorola Data Interface"
#undef CONFIG_OTG_ACM_CONSOLE

/*
 * OTG Mass Storage function
 */
#define CONFIG_OTG_MSC_MODULE 1

/*
 * OTG Mass Storage function options
 */
#define CONFIG_OTG_MSC_VENDORID 0x22b8
#define CONFIG_OTG_MSC_PRODUCTID 0x6426
#define CONFIG_OTG_MSC_BCDDEVICE 0x0101
#define CONFIG_OTG_MSC_MANUFACTURER "Motorola Inc."
#define CONFIG_OTG_MSC_PRODUCT_NAME "MS"
#define CONFIG_OTG_MSC_DESC "MSC BO Configuration"
#define CONFIG_OTG_MSC_HOTPLUG 1
#undef CONFIG_OTG_MSC_REGISTER_TRACE
#define CONFIG_OTG_MSC_NUM_PAGES 0x08

/*
 * OTG Network Function
 */
#define CONFIG_OTG_NETWORK_MODULE 1

/*
 * OTG Network Function options
 */
#define CONFIG_OTG_NETWORK_VENDORID 0x22b8
#define CONFIG_OTG_NETWORK_PRODUCTID 0x6424
#define CONFIG_OTG_NETWORK_BCDDEVICE 0x0101
#define CONFIG_OTG_NETWORK_MANUFACTURER "Motorola Inc."
#define CONFIG_OTG_NETWORK_PRODUCT_NAME "Motorola USB Device"

/*
 * --
 */
#define CONFIG_OTG_NETWORK_BLAN 1

/*
 * BLAN Network Function options
 */
#define CONFIG_OTG_NETWORK_BLAN_DESC "BLAN Net Cfg"
#define CONFIG_OTG_NETWORK_BLAN_CRC 1
#define CONFIG_OTG_NETWORK_BLAN_AUTO_CONFIG 1
#undef CONFIG_OTG_NETWORK_BLAN_NONBRIDGED
#undef CONFIG_OTG_NETWORK_SAFE
#undef CONFIG_OTG_NETWORK_CDC
#undef CONFIG_OTG_NETWORK_BASIC
#undef CONFIG_OTG_NETWORK_BASIC2

/*
 * OTG MTP Function
 */
#define CONFIG_OTG_MTP_MODULE 1

/*
 * OTG MTP function options
 */
#define CONFIG_OTG_MTP_VENDORID 0x22b8
#define CONFIG_OTG_MTP_PRODUCTID 0x6415
#define CONFIG_OTG_MTP_BCDDEVICE 0x0101
#define CONFIG_OTG_MTP_MANUFACTURER "Motorola Inc."
#define CONFIG_OTG_MTP_PRODUCT_NAME "Motorola USB Device"
#define CONFIG_OTG_MTP_DESC "MTP Configuration"
#define CONFIG_OTG_MTP_HOTPLUG 1

/*
 * OTG PBG Function
 */
#define CONFIG_OTG_PBG_MODULE 1

/*
 * OTG PBG function options
 */
#define CONFIG_OTG_PBG_VENDORID 0x22b8
#define CONFIG_OTG_PBG_PRODUCTID 0x6411
#define CONFIG_OTG_PBG_BCDDEVICE 0x0101
#define CONFIG_OTG_PBG_MANUFACTURER "Motorola Inc."
#define CONFIG_OTG_PBG_PRODUCT_NAME "Motorola USB Device"
#define CONFIG_OTG_PBG_DESC "PTP Configuration"
#define CONFIG_OTG_PBG_HOTPLUG 1

/*
 * Synchronous Serial Interfaces (SSI)
 */

/*
 * MMC/SD Card support
 */
#define CONFIG_MMC 1
#undef CONFIG_MMC_DEBUG
#define CONFIG_MMC_BLOCK 1
#undef CONFIG_MMC_BLOCK_BROKEN_RFD
#undef CONFIG_MMC_WBSD
#define CONFIG_MMC_MXC 1

/*
 * profiler support
 */

/*
 * Power IC support
 */
#define CONFIG_MOT_POWER_IC 1
#define CONFIG_MOT_POWER_IC_ATLAS 1
#undef CONFIG_USR_BLK_DEV
#undef CONFIG_LINEARVIBRATOR

/*
 * AP Logger Hooks
 */
#define CONFIG_APLOGGER 1
#define CONFIG_SIM_SUPPORT 1

/*
 * MontaVista System tools
 */
#undef CONFIG_ILATENCY
#undef CONFIG_KFI
#undef CONFIG_PRIORITIZED_OOM_KILL

/*
 * Kernel hacking
 */
#define CONFIG_DEBUG_KERNEL 1
#undef CONFIG_MAGIC_SYSRQ
#undef CONFIG_PRINTK_TIME
#undef CONFIG_SCHEDSTATS
#undef CONFIG_DEBUG_SLAB
#undef CONFIG_DEBUG_PREEMPT
#undef CONFIG_WAKEUP_TIMING
#undef CONFIG_CRITICAL_PREEMPT_TIMING
#undef CONFIG_CRITICAL_IRQSOFF_TIMING
#undef CONFIG_DEBUG_KOBJECT
#define CONFIG_DEBUG_BUGVERBOSE 1
#define CONFIG_DEBUG_INFO 1
#define CONFIG_FRAME_POINTER 1
#undef CONFIG_KGDB
#undef CONFIG_DEBUG_USER
#undef CONFIG_DEBUG_WAITQ
#define CONFIG_DEBUG_ERRORS 1
#undef CONFIG_DEBUG_LL

/*
 * Security options
 */
#undef CONFIG_KEYS
#define CONFIG_SECURITY 1
#undef CONFIG_SECURITY_NETWORK
#undef CONFIG_SECURITY_CAPABILITIES
#undef CONFIG_SECURITY_SECLVL
#undef CONFIG_SECURITY_SELINUX

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#undef CONFIG_CRYPTO_HMAC
#undef CONFIG_CRYPTO_NULL
#undef CONFIG_CRYPTO_MD4
#undef CONFIG_CRYPTO_MD5
#define CONFIG_CRYPTO_SHA1 1
#undef CONFIG_CRYPTO_SHA256
#undef CONFIG_CRYPTO_SHA512
#undef CONFIG_CRYPTO_WP512
#undef CONFIG_CRYPTO_DES
#undef CONFIG_CRYPTO_BLOWFISH
#undef CONFIG_CRYPTO_TWOFISH
#undef CONFIG_CRYPTO_SERPENT
#undef CONFIG_CRYPTO_AES
#undef CONFIG_CRYPTO_CAST5
#undef CONFIG_CRYPTO_CAST6
#undef CONFIG_CRYPTO_TEA
#undef CONFIG_CRYPTO_ARC4
#undef CONFIG_CRYPTO_KHAZAD
#undef CONFIG_CRYPTO_ANUBIS
#undef CONFIG_CRYPTO_DEFLATE
#undef CONFIG_CRYPTO_MICHAEL_MIC
#undef CONFIG_CRYPTO_CRC32C
#undef CONFIG_CRYPTO_TEST

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT 1
#undef CONFIG_CRC16
#define CONFIG_CRC32 1
#undef CONFIG_LIBCRC32C
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1

/*
 * Fast Real-Time Domain
 */
#undef CONFIG_FRD

/*
 * Fast Real-Time Domain Advanced Options
 */

/*
 * MXC support drivers
 */

/*
 * MXC IPU
 */
#define CONFIG_MXC_IPU 1
#define CONFIG_MXC_IPU_PF 1
#define CONFIG_MOT_FEAT_IPU_PP 1

/*
 * MXC SPI support
 */
#define CONFIG_MXC_SPI 1
#define CONFIG_MXC_SPI_SELECT1 1
#define CONFIG_MXC_SPI_SELECT2 1

/*
 * MXC SSI support
 */
#define CONFIG_MXC_SSI 1

/*
 * MXC Digital Audio Multiplexer support
 */
#define CONFIG_MXC_DAM 1

/*
 * SC55112 support
 */
#undef CONFIG_MXC_PMIC_SC55112

/*
 * Advanced Power Management devices
 */

/*
 * MXC Security Drivers
 */
#define CONFIG_MXC_SECURITY_SCC 1
#undef CONFIG_MXC_SECURITY_RNGA
#undef CONFIG_MXC_SECURITY_HAC
#define CONFIG_MXC_SECURITY_RTIC 1
#undef CONFIG_MXC_RTIC_TEST_DEBUG
#define CONFIG_MXC_SECURITY_CORE 1

/*
 * SAHARA2 Security Hardware Support
 */
#define CONFIG_MXC_SAHARA 1
#define CONFIG_MXC_SAHARA_USER_MODE 1
#undef CONFIG_MXC_SAHARA_POLL_MODE

/*
 * SDMA
 */
#define CONFIG_MXC_SDMA_API 1

/*
 * MXC MPEG4 Encoder Kernel module support
 */

/*
 * APAL (Audio Driver) support
 */
#define CONFIG_APAL 1
